# migrations/script.py.mako
"""initial_migration_with_warriors_professions_skills

Revision ID: eab1aaf891e1
Revises: 22c8af47ba78
Create Date: 2026-06-15 12:59:20.330124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # ВАЖНО: добавляем импорт sqlmodel


# revision identifiers, used by Alembic.
revision = 'eab1aaf891e1'
down_revision = '22c8af47ba78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skillwarriorlink', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skillwarriorlink', 'level')
    # ### end Alembic commands ###